### ISSUE TITLE
Features #2

### ISSUE THREAD

**Issue by eugeniu14** [robb4/DnDSpells#2]
So, future features:
Filtering and ordering by: 
        Type of action necessary for the casting of said spell; 
        Range of said spells;
        Duration of said spells;
        Concentration (y/n);
        Whether it's a ritual or not;

**Comment by robb4** [comment]
The requested features have been implemented in the following commits:
b010e5c5df7b03a48d18c664571500b69f8efea2
eb73a3cdc9f6e045ddc2d4069cd8ee007fab47ba
54c68bcaf313d44ca5dff9c27541f768d6b75d96
88dc55efee3bb4b85c7317b4693f054200175811
